version: '3.8'

services:
  user-service:
    build:
      context: ./users_service
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./users_service:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-network

  message-service:
    build:
      context: ./messages_service
      dockerfile: Dockerfile
    expose:
      - "8001"
    volumes:
      - ./messages_service:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-network

networks:
  api-network:
    driver: bridge